version: '3.8'
services:
  frontend:
    image: hi-chat-frontend
    container_name: hichat-frontend-c
    ports:
      - '3000:80'
    env_file:
      - frontend.env

  backend:
    image: hi-chat-backend
    container_name: hichat-backend-c
    ports:
      - '5000:5000'
    env_file:
      - backend.env

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
