version: '3.8'
services:
  frontend:
    image: frontend-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: frontend-dev-c
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
